POST http://localhost:5000/posts HTTP/1.1
Content-Type: application/json

{
    "title":"harry potter VI",
    "author":"rowling"
}

### untuk get all data dari posts
GET  http://localhost:5000/posts HTTP/1.1
Content-Type: application/json


### buat edit satu bagian dari property saja (Patch)
# 3 adalah id 
PATCH  http://localhost:5000/posts/3 HTTP/1.1
Content-Type: application/json

{
    "title":"harry potter II"
} 

### buat edit data object keseluruhan (put)
# 3 adalah id 
PUT  http://localhost:5000/posts/3 HTTP/1.1
Content-Type: application/json

{
    "judul":"harry potter IV"
} 

### delete obejct di json (delete)
# 4 adalah id 
Delete  http://localhost:5000/posts/4 HTTP/1.1
Content-Type: application/json
